# Generated by Django 3.0.8 on 2020-10-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'datatype',
            },
        ),
        migrations.CreateModel(
            name='Granularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granularity', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'granularity',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_ibge', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_ibge_memberof', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=10)),
                ('location_type', models.CharField(max_length=45)),
                ('geo_latitude', models.FloatField()),
                ('geo_longitude', models.FloatField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='ReferencePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField()),
                ('until_date', models.DateField()),
            ],
            options={
                'db_table': 'referenceperiod',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15)),
                ('shortname', models.CharField(max_length=100)),
                ('longname', models.CharField(max_length=256)),
                ('definition', models.TextField(max_length=2048)),
                ('datatype', models.ForeignKey(db_column='id_datatype', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.DataType')),
            ],
            options={
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('granularity', models.ForeignKey(db_column='id_granularity', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.Granularity')),
                ('information', models.ForeignKey(db_column='id_information', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.Information')),
                ('location', models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.Location')),
                ('referenceperiod', models.ForeignKey(db_column='id_referenceperiod', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.ReferencePeriod')),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
