# Generated by Django 3.0.7 on 2020-06-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Granularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granularity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_ibge', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_ibge_memberof', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=10)),
                ('location_type', models.CharField(max_length=45)),
                ('geo_latitude', models.FloatField()),
                ('geo_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferencePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField()),
                ('until_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15)),
                ('shortname', models.CharField(max_length=100)),
                ('longname', models.CharField(max_length=256)),
                ('definition', models.TextField(max_length=2048)),
                ('id_datatype', models.OneToOneField(db_column='id_datatype', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('id_granularity', models.ForeignKey(db_column='id_granularity', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.Granularity')),
                ('id_information', models.ForeignKey(db_column='id_information', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.Information')),
                ('id_information_datatype', models.ForeignKey(db_column='id_information_datatype', on_delete=django.db.models.deletion.DO_NOTHING, related_name='information_datatype', to='chart.Information', to_field='id_datatype')),
                ('id_location', models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.Location')),
                ('id_reference_period', models.ForeignKey(db_column='id_reference_period', on_delete=django.db.models.deletion.DO_NOTHING, to='chart.ReferencePeriod')),
            ],
            options={
                'unique_together': {('id_information', 'id_information_datatype', 'id_reference_period', 'id_location', 'id_granularity')},
            },
        ),
    ]
