# Generated by Django 3.0.8 on 2020-07-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
        migrations.AlterModelTable(
            name='datatype',
            table='datatype',
        ),
        migrations.AlterModelTable(
            name='granularity',
            table='granularity',
        ),
        migrations.AlterModelTable(
            name='information',
            table='information',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='referenceperiod',
            table='referenceperiod',
        ),
    ]
